import Link from 'next/link';
import { Board, Timeline, Roles } from '../components/product-visuals';

export default function Home() {
  return <><section className="hero" data-imicue-signal="overview"><div className="container hero-grid"><div><p className="eyebrow">チームの進行管理を、ひとつに。</p><h1>チームの今を、<br />同じ景色に。</h1><p className="hero-lead">タスク、予定、進捗をひとつの場所へ。<br />PACELETで、次に進めることが見つかります。</p><div className="actions"><Link className="button" href="/features/">機能を見る <span aria-hidden>→</span></Link><Link className="button secondary" href="/resources/">製品資料を見る</Link></div></div><Board compact /></div></section>
    <section className="section container problems" data-imicue-signal="problems"><h2>確認のための往復を、減らす。</h2><div className="three-columns">{[['担当が分からない', '誰が進めているのか、毎回聞いて確かめる。'], ['予定が散らばる', 'タスクと会議の情報が、いくつもの場所に分かれる。'], ['進捗が見えない', 'どこまで進んだのか、報告が来るまで分からない。']].map(([title, body], i) => <div key={title}><span className="number">0{i + 1}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
    <section className="section container" id="features"><div className="section-heading"><p className="eyebrow">FEATURES</p><h2>計画から振り返りまで、<br className="mobile-break" />ひとつにつながる。</h2><p>担当と予定を共有して、次に進むための確認をしやすく。</p></div><div className="feature-row" data-imicue-signal="feature-board"><div><span className="blue-line" /><h3>ボードで、<br />次の一手を整理。</h3><p>担当、期限、進行状況をひとつのタスクに。確認待ちの仕事も一覧でき、誰に声をかけるかが分かります。</p><Link className="text-link" href="/features/#board">ボード機能を見る <span aria-hidden>→</span></Link></div><Board /></div><div className="feature-row" data-imicue-signal="feature-timeline"><div><span className="blue-line" /><h3>予定を並べて、<br />無理のない進行に。</h3><p>締め切りと作業の重なりを予定表で確認。変更した予定を同じ場所で共有し、チームで進め方を相談できます。</p><Link className="text-link" href="/features/#timeline">予定表の使い方を見る <span aria-hidden>→</span></Link></div><Timeline /></div></section>
    <section className="section pale" id="security"><div className="container feature-row" data-imicue-signal="security"><div><p className="eyebrow">SECURITY</p><h2>共有の範囲も、<br />チームで決める。</h2><p>プロジェクトごとにメンバーと役割を設定。更新する人と閲覧する人を分けて、必要な情報を共有します。</p><Link className="text-link" href="/resources/">共有設定を資料で確認する <span aria-hidden>→</span></Link></div><Roles /></div></section>
    <section className="section container" id="cases"><div className="section-heading left"><p className="eyebrow">STORIES</p><h2>チームに合わせた、進め方。</h2><p>役割や働く場所が違うチームを想定した、架空の活用例です。</p></div><div className="case-grid"><article className="case-card" data-imicue-signal="case-creative"><div className="case-art squares" aria-hidden><i /><i /><i /></div><div><p className="eyebrow">制作チーム</p><h3>担当と確認待ちを、<br />同じボードで。</h3><p>企画・制作・確認の流れを整理。次の担当へ渡すタイミングをそろえます。</p><Link className="text-link" href="/cases/#creative">制作チームの事例を見る →</Link></div></article><article className="case-card" data-imicue-signal="case-operations"><div className="case-art circles" aria-hidden><i /><i /><i /></div><div><p className="eyebrow">複数拠点のチーム</p><h3>場所が違っても、<br />進捗を見渡せる。</h3><p>各拠点の作業と引き継ぎを一覧。全体の予定と合わせて確認します。</p><Link className="text-link" href="/cases/#operations">複数拠点の事例を見る →</Link></div></article></div></section>
    <section className="section container" id="pricing"><div data-imicue-signal="pricing"><div className="section-heading"><p className="eyebrow">PLANS</p><h2>チームの規模に合わせて。</h2><p>利用する人数と、共有したい範囲から考えるプランです。</p></div><div className="table-scroll" tabIndex={0} role="region" aria-label="プラン比較表"><table><caption className="sr-only">架空のプランの比較</caption><thead><tr><th scope="col">プラン</th><th scope="col">Starter<small>無料の想定</small></th><th scope="col">Team<small>月額プランの想定</small></th><th scope="col">Organization<small>個別相談の想定</small></th></tr></thead><tbody><tr><th scope="row">共有ボード</th><td>小さなチームで</td><td>複数のチームで</td><td>組織全体で</td></tr><tr><th scope="row">チーム横断</th><td>ひとつのチーム</td><td>チーム間の連携</td><td>拠点をまたぐ管理</td></tr><tr><th scope="row">導入サポート</th><td>利用ガイド</td><td>運用の相談</td><td>移行の相談</td></tr></tbody></table></div><p className="small centered">デモ用の架空プランです。申し込みや決済は行いません。</p></div></section>
    <section className="section container faq" id="faq"><div className="section-heading"><p className="eyebrow">FAQ</p><h2>よくあるご質問</h2></div><article><h3>担当者ごとに共有範囲を変えられますか？</h3><p>プロジェクトごとに管理・編集・閲覧の役割を分ける想定です。プランとの違いは製品資料にまとめています。</p><Link href="/resources/">プランと共有設定を確認する →</Link></article><article data-imicue-signal="faq-migration"><h3>データの移行は相談できますか？</h3><p>既存のタスクの分け方や担当の決め方を整理してから、移す順序を考えます。チームごとの進め方はお問い合わせの相談項目です。</p><Link href="/contact/">移行について相談する →</Link></article><article data-imicue-signal="rollout"><h3>導入までの流れを知りたい</h3><p>現在の運用を整理し、小さなプロジェクトで試して、共有範囲を広げる流れを想定しています。担当や権限の決め方も一緒に整理します。</p><Link href="/contact/">チームの運用について相談する →</Link></article></section>
    <section className="container cta-band" data-imicue-protect><div><h2>自分たちの進め方を、整理する。</h2><p>製品の全体像を資料で。チームごとの進め方は相談で。</p></div><div className="actions"><Link className="button" href="/resources/">製品資料を見る →</Link><Link className="button secondary" href="/contact/">導入について相談する</Link></div></section>
  </>;
}
